export enum CollaboratorRole {
	Advisor = 'Advisor',
	Artist = 'Artist',
	CoWriter = 'CoWriter',
	Colorist = 'Colorist',
	CoverArtist = 'CoverArtist',
	CreativeDirector = 'CreativeDirector',
	Editor = 'Editor',
	Illustrator = 'Illustrator',
	Inker = 'Inker',
	Letterer = 'Letterer',
	Penciler = 'Penciler',
	Translator = 'Translator',
	Writer = 'Writer',
}
